name: Simon Lister
favicon: null
layout_spectrum: 0.8919397664722055
typography_spectrum: 0.8253368530422449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9929134051781148
  lightness: 0.29813384963199496
  saturation: 0.48893272364512086
  rhythmicContrast: 0.3478375182021409
purpose: []
